import { readFile, writeFile, mkdir } from "node:fs/promises";
const artifact = JSON.parse(
  await readFile("contracts/out/Guestbook.sol/Guestbook.json", "utf8"),
);
await mkdir("shared", { recursive: true });
await writeFile(
  "shared/abi.ts",
  `// Generated by npm run compile. Do not edit.\nexport const abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
console.log("Contract compiled. Shared TypeScript ABI regenerated.");
