import { readFileSync, writeFileSync } from 'node:fs'

// ABI comes from Forge, never from a hand-written duplicate.
const artifact = JSON.parse(readFileSync('out/Registry.sol/Registry.json', 'utf8'))
const deployment = JSON.parse(readFileSync('deployments/sepolia.json', 'utf8'))
if (deployment.chainId !== 11155111) throw new Error('Expected Sepolia deployment metadata.')
writeFileSync('shared/contract.ts', `// Generated by npm run compile from Foundry output and deployment metadata.
import { sepolia } from 'viem/chains'
import type { Address } from 'viem'

export const chain = sepolia
export const address: Address | undefined = ${deployment.address ? JSON.stringify(deployment.address) : 'undefined'}
export const abi = ${JSON.stringify(artifact.abi, null, 2)} as const
`)
console.log('Exported shared/contract.ts (chain, address, Foundry ABI).')
